// <auto-generated />
using System;
using CouponService.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CouponService.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181110112542_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CouponService.Domain.Models.CouponCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<int>("CouponManagementId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsUsed");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CouponManagementId");

                    b.ToTable("CouponCodes");
                });

            modelBuilder.Entity("CouponService.Domain.Models.CouponManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Description");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(11,2)");

                    b.Property<int>("DiscountType");

                    b.Property<DateTime>("ExpireDate");

                    b.Property<bool>("IsBulk");

                    b.Property<bool>("IsCanceled");

                    b.Property<bool>("IsForOneUse");

                    b.Property<bool>("IsInfinite");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UpdatedBy");

                    b.Property<bool>("isForA");

                    b.Property<bool>("isForB");

                    b.HasKey("Id");

                    b.ToTable("CouponManagements");
                });

            modelBuilder.Entity("CouponService.Domain.Models.CouponCode", b =>
                {
                    b.HasOne("CouponService.Domain.Models.CouponManagement", "CouponManagement")
                        .WithMany("Codes")
                        .HasForeignKey("CouponManagementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
